image: docker:latest

services:
  - docker:dind

stages:
  - release
  - deploy

variables:
  ECR_REPO: "$ECR_REPO"
  AWS_REGION: "us-east-1"
  LOCAL_REPO: "local"
  accessKeyId: "$accessKeyId"
  secretAccessKey: "$secretAccessKey"

Release Docker Image:
  stage: release
  script: 
    - apk add --no-cache py-pip
    - pip install awscli --break-system-packages
    - aws configure set aws_access_key_id $accessKeyId
    - aws configure set aws_secret_access_key $secretAccessKey
    - aws configure set default.region $AWS_REGION
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
    - docker build -t $LOCAL_REPO . # attach current code to a local docker image
    - docker tag $LOCAL_REPO:latest $ECR_REPO:latest # attach local docker image to remote docker image
    - docker push $ECR_REPO:latest # push remote docker image
  only:
    - master
      
Deploy Lambda Code:
  stage: deploy
  script:
    - apk add --no-cache py-pip
    - pip install awscli --break-system-packages
    - aws configure set aws_access_key_id $accessKeyId
    - aws configure set aws_secret_access_key $secretAccessKey
    - aws configure set default.region $AWS_REGION
    - aws lambda update-function-code --function-name down-ytb --image-uri $ECR_REPO:latest
  only:
    - master