services:
  lambda:
    environment:
      bucket: ${bucket}
      accessKeyId: ${accessKeyId}
      secretAccessKey: ${secretAccessKey}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 3002:3002
    volumes:
      - ./:/app
      - /app/node_modules