frameworkVersion: "3"
service: lambda

plugins:
    - serverless-offline
    - serverless-s3-local

package:
    exclude:
        - .git
        - .gitignore
        - .serverless**
        - events/*.json
        - README.md
  
provider:
    name: aws
    runtime: nodejs16.x
    timeout: 200
    environment:
        bucket: ${env:bucket}
        accessKeyId: ${env:accessKeyId}
        secretAccessKey: ${env:secretAccessKey}
        TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
        TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}

custom:
    serverless-offline:
        host: 0.0.0.0
        port: 3003
        resourceRoutes: true
    s3:
        host: localhost
        port: 3003
        directory: /tmp/s3

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
        
functions:
  getYoutubeVideo:
    handler: index.handler
    timeout: 200
    events:
      - httpApi:
          path: /
          method: get
  postYoutubeVideo:
    handler: index.handler
    timeout: 200
    events:
      - httpApi:
          path: /
          method: post